// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://fusionconnectgroup.com/
// Generated: 2026-09-07T09:37:07.492Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary';
export type ColorHex  = '#e5e7eb' | '#0f1114' | '#6b7280' | '#4b5563' | '#111827' | '#000000' | '#d1d5db' | '#ffffff' | '#f97316' | '#f3f4f6' | '#9ca3af' | '#374151' | '#27272a';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '300' | '500' | '600' | '700';

export type SpacingToken = '1px' | '40px' | '48px' | '64px' | '80px' | '96px' | '128px' | '141px' | '160px' | '170px' | '213px';

export type RadiusToken = '2px' | '6px' | '11px' | '15px' | '24px' | '32px' | '50px' | '999px' | '9999px';

export type DurationToken = '75ms' | '100ms' | '180ms' | '300ms' | '500ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
