// Framer Motion presets — generated by designlang (motionlang)
// Source: https://fusionconnectgroup.com/
// 2026-09-07T09:37:07.663Z
//
//   import { transitions, variants } from './fusionconnectgroup.com-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  custom1: [0.4, 0, 0.2, 1], // 39× on page
  easeOut: [0.23, 1, 0.32, 1], // 12× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.075,
  xs: 0.1,
  sm: 0.18,
  md: 0.3,
  lg: 0.5,
  xl: 1,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.18, ease: easings.custom1 },
  fast:  { duration: 0.100, ease: easings.custom1 },
  slow:  { duration: 0.324, ease: easings.custom1 },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.045 } },
  },
};

export default { easings, durations, transitions, variants };
