// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://open.fusionconnectgroup.com/home
// Generated: 2026-09-07T09:40:20.004Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#e2e4e9' | '#ffffff' | '#0f172a' | '#f97316' | '#0f1114' | '#6b7280' | '#64748b' | '#52525b' | '#3f3f46' | '#020617' | '#22c55e' | '#1f1f1f' | '#fff7ed' | '#c2410c' | '#334155' | '#fed7aa' | '#182231' | '#000000' | '#10b981';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'SF Pro Display';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700' | '650';

export type SpacingToken = '2px' | '24px' | '28px' | '40px' | '48px' | '64px' | '78px' | '88px' | '112px' | '192px' | '272px' | '288px';

export type RadiusToken = '4px' | '8px' | '16px' | '50px' | '999px' | '9999px';

export type DurationToken = '70ms' | '90ms' | '180ms' | '260ms' | '820ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
