// Framer Motion presets — generated by designlang (motionlang)
// Source: https://open.fusionconnectgroup.com/home
// 2026-09-07T09:40:20.010Z
//
//   import { transitions, variants } from './open.fusionconnectgroup.com-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.18, 0.86, 0.32, 1], // 24× on page
  custom2: [0.4, 0, 0.2, 1], // 21× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.07,
  xs: 0.09,
  sm: 0.18,
  md: 0.26,
  xl: 0.82,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.18, ease: easings.easeOut },
  fast:  { duration: 0.100, ease: easings.easeOut },
  slow:  { duration: 0.324, ease: easings.easeOut },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.045 } },
  },
};

export default { easings, durations, transitions, variants };
